### ISSUE TITLE
Wrong method name in wiki: #depth(depth)  -> #at_depth

### ISSUE THREAD

**Issue by joshua5201** [sjke/pg_ltree#26]
https://github.com/sjke/pg_ltree/wiki/List-of-methods-for-work-with-LTree

Class Methods:

    #roots Root nodes
    #at_depth(depth) Nodes on the depth
    #leaves Leaves nodes
    #where_path_liked Nodes when path liked the lquery

**Comment by sjke** [comment]
Fixed.

@joshua5201 thank for the typo found.
