### ISSUE TITLE
Support for Rails 6.0

### ISSUE THREAD

**Issue by jandillmann** [sjke/pg_ltree#28]
Now that Rails 6.0 is released, would it be possible to loosen the Active Record dependency to allow using this gem in Rails 6 projects?

**Comment by francesco-loreti** [comment]
https://github.com/francesco-loreti/pg_ltree

**Comment by kreintjes** [comment]
@francesco-loreti could you please create a PR for this? Or @sjke you want to fix this?
Due to locks we can now use this gem with the Rails 6 release candidate, but not with the official 6.0.0 (or 6.0.1) release.

**Comment by sjke** [comment]
@francesco-loreti , @jandillmann , @kreintjes 
Rasil6 support was released in v1.1.8: https://github.com/sjke/pg_ltree/releases/tag/v1.1.8

**Comment by kreintjes** [comment]
Nice, tnx!
