### ISSUE TITLE
.destroy removes all nodes on same level

### ISSUE THREAD

**Issue by borisd** [sjke/pg_ltree#31]
Currently a call to model.destroy will remove the model AND remove all other models on the same depth of tree (instead of it's children)

```ruby
Space Destroy (1.4ms)  DELETE FROM "spaces" WHERE "spaces"."id" = $1  [["id", 141]]
Space Destroy (0.7ms)  DELETE FROM "spaces" WHERE (spaces.path <@ '133.134.137')
```

Should be:

```ruby
Space Destroy (0.7ms)  DELETE FROM "spaces" WHERE (spaces.path <@ '133.134.137.141')
```

**Comment by sjke** [comment]
@borisd thx you the issue, but seems that the gem working correctly (I updated and added tests to check your error)

**Comment by borisd** [comment]
Hi, 

Looks like the fault was on my side, as I used the path to only holds the relative path of the node.

So my "New York" node's path is "World.USA" not "World.USA.NewYork"  (Still kinda makes sense to me)
